// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnrV9oGHNoEO8aMOOJEnnzZZxhok_HFSQ',
    appId: '1:376896115846:web:0ae7dcdf58d90e9cedad07',
    messagingSenderId: '376896115846',
    projectId: 'book-store-18',
    authDomain: 'book-store-18.firebaseapp.com',
    storageBucket: 'book-store-18.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAfLP0Y7Xhaokkgxi-lNskx4N3GBD_AJ_g',
    appId: '1:376896115846:android:4a0e5d735e6f9111edad07',
    messagingSenderId: '376896115846',
    projectId: 'book-store-18',
    storageBucket: 'book-store-18.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbEmzjTf5543aSJ4v0MWuJfrz5VNAB0jg',
    appId: '1:376896115846:ios:ab36c0ced57f744dedad07',
    messagingSenderId: '376896115846',
    projectId: 'book-store-18',
    storageBucket: 'book-store-18.firebasestorage.app',
    iosBundleId: 'com.example.bookStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbEmzjTf5543aSJ4v0MWuJfrz5VNAB0jg',
    appId: '1:376896115846:ios:ab36c0ced57f744dedad07',
    messagingSenderId: '376896115846',
    projectId: 'book-store-18',
    storageBucket: 'book-store-18.firebasestorage.app',
    iosBundleId: 'com.example.bookStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnrV9oGHNoEO8aMOOJEnnzZZxhok_HFSQ',
    appId: '1:376896115846:web:0aba59be77e76cb8edad07',
    messagingSenderId: '376896115846',
    projectId: 'book-store-18',
    authDomain: 'book-store-18.firebaseapp.com',
    storageBucket: 'book-store-18.firebasestorage.app',
  );
}
